create table if not exists public.solo_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  persona text not null check (persona in ('mani', 'harti')),
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, persona)
);

alter table public.solo_snapshots enable row level security;

create policy "Users can read their own snapshots"
on public.solo_snapshots
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own snapshots"
on public.solo_snapshots
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own snapshots"
on public.solo_snapshots
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
